version: '3.8'

services:
  go-app:
    image: golang:1.23.1
    container_name: go-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: go run ./cmd/api
    depends_on:
      - sqlite

  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite
    volumes:
      - sqlite-data:/sqlite

volumes:
  sqlite-data:
    driver: local
